import React, { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Package, CheckCircle2 } from 'lucide-react';
import { getOrder, formatPrice } from '../../services/api';

const steps = ['pending', 'processing', 'shipped', 'delivered'];
export default function OrderDetails() {
    const { id } = useParams();
    const [state, setState] = useState({ loading: true, order: null, error: '' });
    useEffect(() => { getOrder(id).then((order) => setState({ loading: false, order, error: '' })).catch((error) => setState({ loading: false, order: null, error: error.message })); }, [id]);
    if (state.loading) return <div className="container-site py-12 text-sm text-slate-500">Loading order details...</div>;
    if (state.error || !state.order) return <div className="container-site py-12"><div role="alert" className="rounded-xl bg-rose-50 p-5 text-sm font-semibold text-rose-700">Unable to load this order. {state.error}</div></div>;
    const order = state.order; const current = steps.indexOf(order.status);
    return <div className="container-site py-8 sm:py-12"><Link to="/my-orders" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-brand-700"><ArrowLeft size={16} /> Back to orders</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-brand-600">Order details</p><h1 className="mt-1 font-display text-3xl font-bold text-slate-900">{order.order_number}</h1><p className="mt-1 text-sm text-slate-500">Placed {new Date(order.created_at).toLocaleString()}</p></div><div className="flex gap-2"><span className="badge bg-slate-100 text-slate-700">Order: {order.status}</span><span className="badge bg-amber-100 text-amber-700">Payment: {order.payment_status}</span></div></div><div className="mt-8 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="card p-5 sm:p-6"><h2 className="font-display text-lg font-bold text-slate-900">Products</h2><div className="mt-4 divide-y divide-slate-100">{(order.items || []).map((item) => <div key={item.id} className="flex items-center gap-4 py-4"><div className="flex h-14 w-14 items-center justify-center rounded-xl bg-slate-100 text-brand-600"><Package size={22} /></div><div className="min-w-0 flex-1"><p className="font-semibold text-slate-800">{item.product_name}</p><p className="text-xs text-slate-500">Qty {item.quantity} · {formatPrice(Number(item.product_price))} each</p></div><strong>{formatPrice(Number(item.subtotal))}</strong></div>)}</div><div className="mt-5 border-t border-dashed border-slate-200 pt-4"><div className="flex justify-between text-sm text-slate-500"><span>Subtotal</span><span>{formatPrice(Number(order.subtotal))}</span></div><div className="mt-2 flex justify-between text-sm text-slate-500"><span>Delivery</span><span>{formatPrice(Number(order.delivery_fee))}</span></div><div className="mt-3 flex justify-between font-display text-lg font-bold text-slate-900"><span>Total</span><span>{formatPrice(Number(order.total))}</span></div></div></section><aside className="space-y-6"><section className="card p-5"><h2 className="font-display text-lg font-bold text-slate-900">Delivery details</h2><div className="mt-4 space-y-2 text-sm text-slate-600"><p className="font-semibold text-slate-800">{order.full_name}</p><p>{order.email}</p><p>{order.phone}</p><p>{order.address}, {order.city}, {order.country}</p></div></section><section className="card p-5"><h2 className="font-display text-lg font-bold text-slate-900">Order timeline</h2><div className="mt-4 space-y-3">{steps.map((step, index) => <div key={step} className={`flex items-center gap-3 text-sm ${index <= current ? 'font-semibold text-brand-700' : 'text-slate-400'}`}><CheckCircle2 size={17} />{step}</div>)}</div></section></aside></div></div>;
}
